<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="racecar">

    <xacro:include filename="robot_colors.xacro" />
    <xacro:include filename="inertial_macros.xacro" />

    <xacro:property name="wheelbase" value="0.311" />
    <xacro:property name="width" value="0.289" />
    <xacro:property name="height" value="0.178" />
    <xacro:property name="ground_offset" value="0.04" /> <!--Measure this-->
    <xacro:property name="wheel_radius" value="0.07112" /> <!--Verify this-->
    <xacro:property name="wheel_length" value="0.086" /> <!--Verify this-->
    <xacro:property name="laser_distance_from_base_link" value="0.275" /> <!--Measure this-->
    <xacro:property name="laser_height" value="0.05" /> <!--Measure this-->
    <xacro:property name="laser_radius" value="0.026" /> <!--Measure this-->


    <!--BASE LINK-->
    <link name="base_link">
        <visual>
            <origin xyz="${wheelbase/2} 0 ${ground_offset+height/2}"/>
            <geometry>
                <box size="${wheelbase} ${width} ${height}"/>
            </geometry>
            <material name="white"/>
        </visual>
        <collision>
            <origin xyz="${wheelbase/2} 0 ${ground_offset+height/2}"/>
            <geometry>
                <box size="${wheelbase} ${width} ${height}"/>
            </geometry>
            <material name="white"/>
        </collision>
        <xacro:inertial_box mass="1.69" x="${wheelbase}" y="${width}" z="${height}">
            <origin xyz="${wheelbase/2} 0 ${ground_offset+height/2}" rpy="0 0 0"/>
        </xacro:inertial_box>
    </link>
    <gazebo reference="base_link">
        <material>Gazebo/White</material>
    </gazebo>       
    
    <!--LIDAR-->
    <joint name="base_to_laser_model" type="fixed">
        <parent link="base_link"/>
        <child link="laser_model"/>
        <origin xyz="${laser_distance_from_base_link} 0 ${ground_offset+height+(laser_height/2)}"/>
    </joint>
    <link name="laser_model">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_height}"/>
            </geometry>
            <material name="black"/>
        </collision>
    </link>
    <gazebo reference="laser_model">
        <material>Gazebo/Black</material>
    </gazebo>  

    <!--BACK LEFT DRIVE WHEEL-->
    <joint name="base_to_back_left_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="back_left_wheel"/>
        <origin xyz="0 ${(wheel_length+width)/2} ${wheel_radius}" rpy="-${pi/2} 0 0"/>
        <axis xyz="0 0 1"/>
    </joint>
    <link name="back_left_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="orange"/>            
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="back_left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>  
 
    <!--BACK RIGHT DRIVE WHEEL-->
    <joint name="base_to_back_right_wheel" type="continuous">
        <parent link="base_link"/>
        <child link="back_right_wheel"/>
        <origin xyz="0 ${-(wheel_length+width)/2} ${wheel_radius}" rpy="${pi/2} 0 0"/>
        <axis xyz="0 0 -1"/>
    </joint>

    <link name="back_right_wheel">
        <visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="orange"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="orange"/>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="back_right_wheel">
        <material>Gazebo/Orange</material>
    </gazebo> 

    <!--FRONT LEFT-->
    <joint name="front_left_hinge_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_left_hinge"/>
        <origin xyz="${wheelbase} ${(wheel_length+width)/2} ${wheel_radius}" rpy="0 ${-pi/2} 0"/>
        <limit upper="0.5236" lower="-0.5236" velocity="20" effort="1"/>
        <axis xyz="1 0 0"/>
    </joint>

    <link name="front_left_hinge">
		<visual>
            <geometry>
                <cylinder radius="0.01" length="0.01"/>
            </geometry>
            <material name="blue"/>
		</visual>
        <collision>
            <geometry>
                <cylinder radius="0.01" length="0.04"/>
            </geometry>
            <material name="blue"/>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="front_left_wheel">
        <material>Gazebo/Blue</material>
    </gazebo>

    <joint name="front_left_hinge_to_wheel" type="continuous">
		<parent link="front_left_hinge"/>
		<child link="front_left_wheel"/>
    </joint>

    <link name="front_left_wheel">
		<visual>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
		</visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
            <material name="blue"/>
            <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>
    <gazebo reference="front_left_wheel">
        <material>Gazebo/Black</material>
    </gazebo>

    <!--FRONT RIGHT-->
    <joint name="front_right_hinge_joint" type="revolute">
        <parent link="base_link"/>
        <child link="front_right_hinge"/>
        <origin xyz="${wheelbase} ${-(wheel_length+width)/2} ${wheel_radius}" rpy="0 ${-pi/2} 0"/>
        <limit upper="0.5236" lower="-0.5236" velocity="20" effort="1"/>
        <axis xyz="1 0 0"/>
    </joint>

    <link name="front_right_hinge">
		<visual>
            <geometry>
                <cylinder radius="0.01" length="0.01"/>
            </geometry>
            <material name="blue"/>
		</visual>
        <collision>
            <geometry>
                <cylinder radius="0.01" length="0.04"/>
            </geometry>
            <material name="blue"/>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="0.04" radius="0.01">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

    <joint name="front_right_hinge_to_wheel" type="continuous">
        <parent link="front_right_hinge"/>
        <child link="front_right_wheel"/>
    </joint>

    <link name="front_right_wheel">
        <visual>
        <geometry>
            <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
        </geometry>
        <material name="blue"/>
        <origin xyz="0 0 0" rpy="${pi/2} 0 0"/>
        </visual>
        <collision>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.1" length="${wheel_length}" radius="${wheel_radius}">
            <origin xyz="0 0 0" rpy="0 0 0"/>
        </xacro:inertial_cylinder>
    </link>

</robot>