<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <!-- Constants for robot dimensions -->
  <xacro:property name="PI" value="3.1415926535897931"/>
  <xacro:property name="base_mass" value="4.0" /> <!-- arbitrary value for base mass -->
  <xacro:property name="base_width" value="0.260" />
  <xacro:property name="base_length" value="0.525" />
  <xacro:property name="base_height" value="0.060" />
  <xacro:property name="wheelbase" value="0.289" />
  <xacro:property name="wheel_mass" value="0.34055" /> <!-- arbitrary value for wheel mass -->
  <xacro:property name="wheel_len" value="0.055" />
  <xacro:property name="wheel_radius" value="0.05" />
  <!-- <xacro:property name="wheeltrack" value="" -->

  <!-- Base Link -->
  <link name="base_link" />

  <!-- Base Footprint -->
  <joint name="base_footprint_joint" type="fixed">
    <parent link="base_link"/>
    <child link="base_footprint"/>
    <origin xyz="0 0 0" rpy="0 0 0"/>
  </joint>

  <link name="base_footprint" />

  <!-- Chassis -->

  <link name="chassis_link">
    <collision>
      <origin xyz="${wheelbase/2} 0 ${base_height/2 + wheel_radius}" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
    </collision>

    <visual>
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <geometry>
        <box size="${base_length} ${base_width} ${base_height}"/>
      </geometry>
      <material name="green"/>
    </visual>

    <xacro:inertial_box mass="${base_mass}" x="${wheelbase}" y="${base_width}" z="${base_height}">
      <origin xyz="${wheelbase/2} 0 ${base_height/2 + wheel_radius}" rpy="0 0 0"/>
    </xacro:inertial_box>      
    </link>

    <joint name="chassis_joint" type="fixed">
      <parent link="base_link"/>
      <child link="chassis_link"/>
      <origin xyz="${wheelbase/2} 0 ${base_height/2 + wheel_radius}" rpy="0 0 0"/>
      <axis xyz="0 0 1"/>
      <dynamics damping="0.2"/>
    </joint>


    <!-- rear wheels -->

    <!-- virtual rear wheel -->

    <link name="virtual_rear_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="0.01" radius="${wheel_radius}"/>
        </geometry>
        <material name="invisible"/>
      </visual>
    </link>

    <joint name="virtual_rear_wheel_joint" type="continuous">
      <parent link="chassis_link"/>
      <child link="virtual_rear_wheel"/>
      <origin xyz="-${wheelbase/2} 0 -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="0.5"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- rear right wheel -->

    <link name="rear_right_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      </xacro:inertial_cylinder>      

    </link>

    <joint name="rear_right_wheel_joint" type="continuous">
      <parent link="chassis_link"/>
      <child link="rear_right_wheel"/>
      <origin xyz="-${wheelbase/2} ${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="0.5"/>
      <dynamics damping="0.2"/>
      <mimic joint="virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <!-- rear left wheel -->
    <link name="rear_left_wheel">
        <collision>
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
          <geometry>
            <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
          </geometry>
        </collision>

        <visual>
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
          <geometry>
            <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
          </geometry>
          <material name="black"/>
        </visual>

      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      </xacro:inertial_cylinder>          

    </link>

    <joint name="rear_left_wheel_joint" type="continuous">
      <parent link="chassis_link" />
      <child link="rear_left_wheel" />
      <origin xyz="-${wheelbase/2} -${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="1 0 0"/>
      <limit effort="100.0" velocity="0.5"/>
      <dynamics damping="0.2"/>
      <mimic joint="virtual_rear_wheel_joint" multiplier="1.0" offset="0.0"/>
    </joint>

    <!-- front wheels -->

    <!-- virtual front wheel -->

    <link name="virtual_front_wheel">
      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="0.01" radius="${wheel_radius}"/>
        </geometry>
        <material name="invisible"/>
      </visual>
    </link>

    <joint name="virtual_front_wheel_joint" type="revolute">
      <parent link="chassis_link"/>
      <child link="virtual_front_wheel"/>
      <origin xyz="${wheelbase/2} 0 -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.785398" upper="0.785398" effort="1" velocity="1"/>
      <dynamics damping="0.2"/>
    </joint>

    <!-- front right wheel -->


    <link name="front_right_wheel">

      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      </xacro:inertial_cylinder>       
    </link>

    <joint name="front_right_wheel_joint" type="revolute">
      <parent link="chassis_link" />
      <child link="front_right_wheel" />
      <origin xyz="${wheelbase/2} ${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.785398" upper="0.785398" effort="1" velocity="1"/>
      <dynamics damping="0.2"/>
      <!-- <mimic joint="virtual_front_wheel_joint" multiplier="1.0" offset="0.0"/> -->
    </joint>

    <!-- front left steering -->


    <link name="front_left_wheel">
      <collision>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
      </collision>

      <visual>
        <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
        <geometry>
          <cylinder length="${wheel_len}" radius="${wheel_radius}"/>
        </geometry>
        <material name="black"/>
      </visual>

      <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_len}" radius="${wheel_radius}">
          <origin xyz="0 0 0" rpy="${PI/2} 0 ${PI/2}"/>
      </xacro:inertial_cylinder> 

    </link>

    <joint name="front_left_wheel_joint" type="revolute">
      <parent link="chassis_link" />
      <child link="front_left_wheel" />
      <origin xyz="${wheelbase/2} -${base_width/2} -${base_height/2}" rpy="0 0 ${PI/2}"/>
      <axis xyz="0 0 1"/>
      <limit lower="-0.785398" upper="0.785398" effort="1" velocity="1"/>
      <dynamics damping="0.2"/>
      <!-- <mimic joint="virtual_front_wheel_joint" multiplier="0.5" offset="0.0"/> -->
    </joint>


</robot>
