controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true
    
    asc:
      type: ackermann_steering_controller/AckermannSteeringController       
    
    jsc:
      type: joint_state_broadcaster/JointStateBroadcaster
    
asc:
  ros__parameters:

    reference_timeout: 2.0
    front_steering: true
    open_loop: false
    velocity_rolling_window_size: 10
    position_feedback: false
    use_stamped_vel: true

    base_frame_id: base_link

    rear_wheels_names: [back_right_wheel_joint, back_left_wheel_joint]
    front_wheels_names: [front_right_wheel_steer_joint, front_left_wheel_steer_joint]


    wheelbase: 0.311
    front_wheel_track: 0.289
    rear_wheel_track: 0.289
    front_wheels_radius: 0.07112
    rear_wheels_radius: 0.07112
    
    
#jsc:
#  ros__parameters:
#    type: joint_state_controller/JointStateController