controller_manager:
  ros__parameters:
    update_rate: 50  # Hz
    #use_sim_time: true

    jsc:
      type: joint_state_broadcaster/JointStateBroadcaster

    bsc:
      type: bicycle_steering_controller/BicycleSteeringController


bsc:
  ros__parameters:
    wheelbase: 0.289
    front_wheel_radius: 0.05
    rear_wheel_radius: 0.05
    front_steering: true
    reference_timeout: 2.0
    rear_wheels_names: ['virtual_rear_wheel_joint']
    front_wheels_names: ['virtual_front_wheel_joint']
    open_loop: false         # LEAVE THIS AS TRUE UNTIL WE HAVE THE IR SENSOR WORKING
    velocity_rolling_window_size: 1
    base_frame_id: base_link
    odom_frame_id: odom
    enable_odom_tf: true
    twist_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    pose_covariance_diagonal: [0.0, 7.0, 14.0, 21.0, 28.0, 35.0]
    position_feedback: false
    use_stamped_vel: true

#jsc:
#  ros__parameters:
#    type: joint_state_controller/JointStateController    